services:
  - type: cron
    name: assign-alarm
    schedule: '0 0 * * *' # UTC 0시 = 한국 오전 9시
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'python main.py'
    envVars:
      - key: SSU_ID
        value: ${SSU_ID}
      - key: SSU_PW
        value: ${SSU_PW}
      - key: SLACK_APP_TOKEN
        value: ${SLACK_APP_TOKEN}
      - key: SLACK_BOT_TOKEN
        value: ${SLACK_BOT_TOKEN}
      - key: SLACK_SIGNING_SECRET
        value: ${SLACK_SIGNING_SECRET}
